const fs = require('fs');
const path = require('path');

const ROOT_DIR = process.cwd();
const PACKAGE_JSON_PATH = path.join(ROOT_DIR, 'package.json');
const VERSION_JSON_PATH = path.join(ROOT_DIR, 'public', 'version.json');
const VERSION_TS_PATH = path.join(ROOT_DIR, 'lib', 'version.ts');

function generateVersion() {
  const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON_PATH, 'utf-8'));
  const version = pkg.version;
  const buildTime = new Date().toISOString();

  // Generate public/version.json (will be copied to out/ during static export)
  const versionJson = { version, buildTime };
  fs.writeFileSync(VERSION_JSON_PATH, JSON.stringify(versionJson, null, 2));
  console.log(`✅ Generated public/version.json: v${version} (${buildTime})`);

  // Generate lib/version.ts (for code reference)
  const versionTs = `// Auto-generated by scripts/generate-version.js — DO NOT EDIT MANUALLY\nexport const APP_VERSION = "${version}" as const;\nexport const BUILD_TIME = "${buildTime}" as const;\n`;
  fs.writeFileSync(VERSION_TS_PATH, versionTs);
  console.log(`✅ Generated lib/version.ts: v${version}`);
}

generateVersion();
